#!/bin/bash

# Set default values for the arguments if not provided
amount_of_runs=5
cad_path="/home/yangfei/BlenderProc2_Cobot/CAD_model/models_single"
camera_id=0

part_name="insert_mold"
# output_path="/home/yangfei/clean-pvnet/data/FIT/insert_mold_fixed_train" #output should be last argument
output_path="/home/yangfei/clean-pvnet/data/FIT/insert_mold_fixed_test" #output should be last argument

# part_name="mainshell"
# output_path="/home/yangfei/clean-pvnet/data/FIT/mainshell_train" #output should be last argument
# output_path="/home/yangfei/clean-pvnet/data/FIT/mainshell_test" #output should be last argument

# part_name="topshell"
# output_path="/home/yangfei/clean-pvnet/data/FIT/topshell_train" #output should be last argument
# output_path="/home/yangfei/clean-pvnet/data/FIT/topshell_test" #output should be last argument

pose_path="${output_path}/pose"
k_path="${output_path}/k"
mask_path="${output_path}/mask"

# Create the output folder if it doesn't exist
mkdir -p ${output_path}
mkdir -p ${pose_path}
mkdir -p ${k_path}
mkdir -p ${mask_path}

# Execute the rerun.py script
python rerun.py ${1:-amount_of_runs} run ./pvnet.py ${cad_path} ${camera_id} ${part_name} ${output_path}